# Generated by Django 3.2.18 on 2023-05-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Codigo_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'codigo_area',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('muestra', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tipo_examen',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_muestra',
            },
        ),
        migrations.CreateModel(
            name='Valores_Predeterminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('valor_minimo', models.FloatField(blank=True, null=True)),
                ('valor_maximo', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=10)),
                ('decorador', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'valores_predeterminados',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Examen_X_Valores_Predeterminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.ForeignKey(db_column='tipo_examen', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='api.tipo_examen')),
                ('valor_predeterminado', models.ForeignKey(db_column='valor_predeterminado', on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='api.valores_predeterminados')),
            ],
            options={
                'db_table': 'tipo_examen_has_valores_predeterminados',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Examen_X_Tipo_Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(db_column='examen', on_delete=django.db.models.deletion.CASCADE, related_name='muestras_asignadas', to='api.tipo_examen')),
                ('tipo_muestra', models.ForeignKey(db_column='tipo_muestra', on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='api.tipo_muestra')),
            ],
            options={
                'db_table': 'tipo_examen_has_tipo_muestra',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Examen_X_Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(db_column='cargo', on_delete=django.db.models.deletion.CASCADE, related_name='examenes_asigandos', to='api.cargos')),
                ('examen', models.ForeignKey(db_column='examen', on_delete=django.db.models.deletion.CASCADE, related_name='cargo_asignado', to='api.tipo_examen')),
            ],
            options={
                'db_table': 'tipo_examen_has_cargo',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('credencial', models.CharField(max_length=10)),
                ('cargo', models.ForeignKey(db_column='cargo', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='api.cargos')),
                ('persona', models.OneToOneField(db_column='persona', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='api.personas')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=300)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('codigo_telefonico', models.ForeignKey(db_column='codigo_telefonico', on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='api.codigo_area')),
                ('persona', models.OneToOneField(db_column='persona', on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='api.personas')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Muestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_extraccion', models.DateField()),
                ('numero', models.IntegerField()),
                ('lote', models.CharField(blank=True, max_length=8, null=True)),
                ('interno', models.BooleanField(default=True)),
                ('examen', models.ForeignKey(db_column='examen', on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='api.examen')),
                ('personal', models.ForeignKey(db_column='personal', on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='api.personal')),
                ('tipo_muestra', models.ForeignKey(db_column='tipo_muestra', on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='api.tipo_muestra')),
            ],
            options={
                'db_table': 'muestras',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(db_column='paciente', on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='api.paciente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='personal_finalizacion',
            field=models.ForeignKey(blank=True, db_column='personal_finalizacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen_finalizacion', to='api.personal'),
        ),
        migrations.AddField(
            model_name='examen',
            name='personal_registro',
            field=models.ForeignKey(db_column='personal_registro', on_delete=django.db.models.deletion.CASCADE, related_name='examen_registro', to='api.personal'),
        ),
        migrations.AddField(
            model_name='examen',
            name='tipo',
            field=models.ForeignKey(db_column='tipo', on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='api.tipo_examen'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True)),
                ('archivo', models.FileField(upload_to='archivos/%Y/%m/%d')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(db_column='examen', on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='api.examen')),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
    ]
