# Generated by Django 3.2.18 on 2023-05-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tipo_examen_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores_predeterminados',
            name='unidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
